### ISSUE TITLE
2D Gaussian data with 1 unknown variance and known means

### ISSUE THREAD

**Issue by mjvakili** [ErikOsinga/master_research_project#1]

**Comment by ErikOsinga** [comment]
By assuming both dimensions of the Gaussian are unrelated, I can generate data from a 2D gaussian by generating data from two one-D gaussians. (see learning_purposes/2Dgaussian_variance/main.py)

The learning curve is given below for network version 1005. Of which the model settings are saved under learning_purposes/2Dgaussian_variance/modelsettings2.csv

![variables_vs_epochs_1005](https://user-images.githubusercontent.com/12582441/49076056-703df880-f238-11e8-82ca-860ef5417d97.png)

**Comment by mjvakili** [comment]
closing this as it is not relevant anymore
