### ISSUE TITLE
switch to S_8 and Omega_m

### ISSUE THREAD

**Issue by mjvakili** [ErikOsinga/master_research_project#10]
Can you switch to S8 and Omega_m to avoid the problem with degeneracy that we discussed?

**Comment by ErikOsinga** [comment]
Definitely! 
I finally have time to look at this now.. Should I just use the same fiducial parameters, implying fiducial S8 = 0.831?

**Comment by ErikOsinga** [comment]
We decided to not switch to S_8 and Omega_m, so I am closing this
