### ISSUE TITLE
plot Cl for different values of omega_cdm

### ISSUE THREAD

**Issue by mjvakili** [ErikOsinga/master_research_project#6]
Hi Erik,

Can you plot Cl for different values of omega_cdm? This will help you get a sense of how Cl's are sensitive to varying omega_cdm.
Also as a start, can you just estimate one parameter (omega_cdm) with IMNN?
You can keep the rest of the parameters fixed!

**Comment by ErikOsinga** [comment]
Hi, 

I was currently trying it with two parameters (Omega_c and sigma8), but going down to 1 first is a better start. For the two parameter case I had delta_theta = [0.02,0.02], but the differences between the upper and lower derivatives are very low (note the y-axes labels):

![derivatives_visualization_7](https://user-images.githubusercontent.com/12582441/52261788-be533480-292a-11e9-8743-5468abb03e75.png)


Which results in loss curves that just go randomly up and down:
![variables_vs_epochs_7](https://user-images.githubusercontent.com/12582441/52261809-ca3ef680-292a-11e9-8cb0-2c796add58c5.png)


So I will have to think about how to normalize/standardize the Cl's.

**Comment by mjvakili** [comment]
Are these the noisy Cl's? 
Can you try a larger delta_theta and one parameter (omega_cdm) perhaps?

**Comment by ErikOsinga** [comment]
Yes this is from the noisy Cl's.

I don't really have a feeling for how large delta_theta should be for omega_cdm, do you mean an order of magnitude larger?

**Comment by mjvakili** [comment]
yeah perhaps something of order 10^-1!
You can take a look at fig.12 of this paper: https://arxiv.org/pdf/1607.01761.pdf
You might get a feeling of how large delta_theta should be by looking at Delta Cl/Cl given a logarithmic change in omega_m and the errorbars

**Comment by ErikOsinga** [comment]
I implemented the 1 parameter version now, with delta_theta = 0.11 the difference between the upper/lower simulations is still very small:

![derivatives_visualization_1](https://user-images.githubusercontent.com/12582441/52269263-e009e700-293d-11e9-9277-06670d59f1d4.png)

Taking the logarithm of the Cl's doesn't seem to help the network learn either. It is interesting that the loss curves are almost the same whether I take the log or not. I think it will the answer will lie in the standardization of the data/derivatives.

**Comment by mjvakili** [comment]
Can you plot (delta Cl)/Cl (only the theoretical Cl with no noise) as a function of l? 
In the same plot, can you show (sigma Cl /Cl) as a function of l? 
delta Cl = Cl(0.28) - Cl(0.26) ; 
sigma Cl = (var Cl)**0.5

**Comment by ErikOsinga** [comment]
![derivatives_visualization_divided_4](https://user-images.githubusercontent.com/12582441/52286700-f5483b00-2968-11e9-899d-99acc9e3a0d5.png)

**Comment by ErikOsinga** [comment]
The issue with the upper/lower derivatives is now resolved. It was a problem with not correctly rescaling the data and not with the numerical derivative calculation. Closing this issue here.
