### ISSUE TITLE
Getting the imnn to work with more cosmological parameters and more redshift bins

### ISSUE THREAD

**Issue by mjvakili** [ErikOsinga/master_research_project#7]
We should move on two multiple parameters (\Omega_c, \sigma8)
and then to three parameters (\Omega_c, \sigma8, w)

Once we get that to work, we can continue the work with more redshift bins.

**Comment by ErikOsinga** [comment]
Sounds like a good idea, did you have any luck with getting the emulator to work yet? We're definitely going to need this for >1 parameter

**Comment by mjvakili** [comment]
I'm still working on getting the emulator to work. 
In the meantime, can you run the following tests: 

(1) with multiple tomographic bins and \Omega_c  

(2) Single tomographic bin: no interpolation but more restrictive prior for \Omega_c (in order to avoid exploring regions of the parameter space where CLASS is slow)

**Comment by ErikOsinga** [comment]
(1) I am now doing 3 tomographic bins as a start, the free parameter is Omega_m

I rescale the data by taking the negative logarithm of the data, and then flatten it before feeding it into a dense network with 2 layers with 256 nodes each.

The data visualized: 
![data_visualization_train_1](https://user-images.githubusercontent.com/12582441/54883033-23be9e80-4e61-11e9-9297-f57ba87d0d01.png)

The network learning curve:

![variables_vs_epochs_1](https://user-images.githubusercontent.com/12582441/54883047-46e94e00-4e61-11e9-9499-ac9516c5c8da.png)

It seems the network has no problem with this setup.

**Comment by ErikOsinga** [comment]
(2) A more restrictive prior does not work, because the integration hangs for seemingly random cosmologies, not necessarily cosmologies that are far away from the fidicial parameters that I am using

**Comment by mjvakili** [comment]
Okay then it seems like we have to fix the emulator. Can you also run the
ABC to find the posteriors on Omegam?

**Comment by ErikOsinga** [comment]
Yes! Below is the result of ABC. I should note that since we are doing simple linear interpolation it is not very informative, because further and further away from the fiducial parameter the data will be worse and worse. In this way it is also hard to interpret if the network has correctly converged or whether the output summary simply varies linearly because the input simulations now vary linearly with the parameters



![ABC_1_1D_backup2](https://user-images.githubusercontent.com/12582441/54911099-fd931000-4eed-11e9-8fb1-33aa2a8663f5.png)

**Comment by mjvakili** [comment]
While initializing the cosmology with CCL, can you set the 'nonlinear' keyword to halofit to see if that makes any difference?

**Comment by ErikOsinga** [comment]
There is no 'nonlinear' keyword in pyccl.Cosmology, the only keywords that are not simply parameters are
    transfer_function='boltzmann_class',
    matter_power_spectrum='halofit',
    baryons_power_spectrum='nobaryons',
    mass_function='tinker10',
    halo_concentration='duffy2008',
    emulator_neutrinos='strict',

If you mean matter_power_spectrum = 'halofit', this is the default, but when using the emulator for the transfer function the matter_power_spectrum = 'emu' is required or else this error is thrown:

ValueError: matter_power_spectrum 'halofit' can't be used with transfer_function 'emulator'.

**Comment by mjvakili** [comment]
Okay great! Can you set the transfer function to bbks?

**Comment by ErikOsinga** [comment]
The angular power spectrum is quite different for this transfer function than for the default (boltzmann_class)

This is with boltzmann_class (default):
![errorbars_13](https://user-images.githubusercontent.com/12582441/55081155-9ddc6680-509f-11e9-8e57-5b5f4f6f71df.png)


This is for bbks:

![errorbars_14](https://user-images.githubusercontent.com/12582441/55081188-adf44600-509f-11e9-9924-d9af356fce35.png)

**Comment by mjvakili** [comment]
It shouldn't look like this.

I looks like it's only calculating the linear part of the powerspectrum and
not nonlinear part.

**Comment by mjvakili** [comment]
Closing this since this is already resolved
